version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000" # or your backend port
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoapp
    depends_on:
      - mongo

  front:
    build: ./front
    ports:
      - "3000:3000"  # React default dev port
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
